"""Data provenance for the figures a brief carries (#156).

Every data section of a brief names four things — where the figure came from,
when that source was last taken, what it covers (whole network vs a single
site) and the period it spans — plus, for benchmark data, how often it is
refreshed. Until a figure could be traced, nobody could tell whether it was
wrong or merely defined differently: the August 2026 QA round produced two
false reports on exactly that gap, one reconciling campaign CTR against the ad
server rather than the delivery export the product actually reads.

The record lives in ``data/provenance.csv``, alongside the extracts it
describes, so refreshing an extract and restating its as-at date are one
commit. This module is the only reader: deterministic, pure, no LLM. Provenance
is rendered from this data directly into the brief, the deck and the email — it
is never generated by the model, so it cannot drift from what actually produced
the number.

Two sections are per-brief rather than per-registry and are resolved here:
Historical Research takes its dates and base from the study the brief matched,
and the live sources (web research, Google Trends) are dated with the run date.
"""
import csv
import logging
import os
import datetime

logger = logging.getLogger(__name__)

DEFAULT_CSV_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "provenance.csv"
)

# Column order of the registry, and the field order of every entry it yields.
FIELDS = ("section", "source", "as_at", "coverage", "period", "cadence")

# Placeholder for a source with no fixed extract date — it is read live, so its
# as-at date is the date the brief was run.
RUN_DATE_TOKEN = "{run_date}"

# The section whose provenance comes from the matched study rather than the
# registry row, which holds only its unmatched defaults.
HISTORICAL_SECTION = "Historical Research"
TRENDS_SECTION = "Google Trends"

# Label shown against each field, in render order.
_LABELS = (
    ("source", "Source"),
    ("as_at", "As at"),
    ("coverage", "Coverage"),
    ("period", "Period"),
    ("cadence", "Refreshed"),
)

BLOCK_HEADING = "Where these figures come from"


def load_provenance(csv_path=None):
    # type: (str) -> list
    """Read the registry verbatim, one entry per data section, in file order.

    Returns an empty list when the file is missing, so a deployment without it
    shows no provenance rather than failing a brief. That is logged: silence
    would look identical to a brief that genuinely had no sources.
    """
    if csv_path is None:
        csv_path = DEFAULT_CSV_PATH

    if not os.path.exists(csv_path):
        logger.warning("No provenance registry at %s; briefs will carry no "
                       "source attribution.", csv_path)
        return []

    with open(csv_path, newline="", encoding="utf-8") as f:
        entries = []
        for row in csv.DictReader(f):
            entry = {key: (row.get(key) or "").strip() for key in FIELDS}
            if entry["section"]:
                entries.append(entry)
    return entries


def build_provenance(historical_research=None, include_google_trends=True,
                     run_date=None, csv_path=None):
    # type: (dict, bool, datetime.date, str) -> list
    """Resolve the registry against one brief run.

    Sections the brief did not render are dropped — a source line for a section
    that is not there would be its own kind of untraceable. Sections read live
    are dated with ``run_date`` (today by default), and Historical Research is
    re-described from the study that actually matched.
    """
    if run_date is None:
        run_date = datetime.date.today()
    run_date_text = run_date.isoformat()

    resolved = []
    for entry in load_provenance(csv_path):
        section = entry["section"]

        if section == TRENDS_SECTION and not include_google_trends:
            continue
        if section == HISTORICAL_SECTION:
            entry = _resolve_historical(entry, historical_research)
            if entry is None:
                continue

        if entry["as_at"] == RUN_DATE_TOKEN:
            entry = dict(entry, as_at=run_date_text)
        resolved.append(entry)

    return resolved


def _resolve_historical(entry, research):
    # type: (dict, dict) -> dict
    """Describe the matched study, or return None when nothing matched.

    Every field comes from the study's own frontmatter, which the gate already
    carries through (see ``src.historical_research``). A study that states no
    fieldwork dates is left undated rather than dated from anything else — the
    point of the field is that it can be checked.
    """
    if not research or not research.get("relevant"):
        return None

    organisation = (research.get("organisation") or "").strip()
    title = (research.get("title") or "").strip()
    # Study titles usually already lead with the publisher ("Immediate Media
    # Travel Audience Research 2024/25"), so prefixing unconditionally would
    # name it twice.
    if organisation and organisation.lower() in title.lower():
        source = title
    else:
        source = " — ".join(part for part in (organisation, title) if part)

    fieldwork = (research.get("fieldwork") or "").strip()
    # The gate renders fieldwork as "start to end" (or a single date). The study
    # is as-at the end of its fieldwork, which is the later of the two.
    as_at = fieldwork.split(" to ")[-1].strip() if fieldwork else ""

    coverage = entry["coverage"]
    respondents = research.get("total_respondents")
    if respondents:
        coverage = "%s (n=%s)" % (coverage, "{:,}".format(int(respondents)))

    return dict(
        entry,
        source=source or entry["source"],
        as_at=as_at,
        coverage=coverage,
        period=("Fieldwork %s" % fieldwork) if fieldwork else "",
    )


def provenance_for(entries, section):
    # type: (list, str) -> dict
    """The entry for one section, or None when it carries no provenance."""
    for entry in entries or []:
        if entry.get("section") == section:
            return entry
    return None


def format_provenance_line(entry):
    # type: (dict) -> str
    """One labelled line for a section's provenance.

    Fields with nothing behind them are omitted rather than rendered as an
    empty label — "As at:" followed by nothing states less than saying nothing.
    """
    parts = []
    for key, label in _LABELS:
        value = (entry.get(key) or "").strip()
        if value:
            parts.append("%s: %s" % (label, value))
    return " · ".join(parts)


def format_provenance_block(entries, heading=BLOCK_HEADING):
    # type: (list, str) -> str
    """Plain-text provenance for surfaces that carry no structure.

    Used by the email footer and the deck's appendix, so the same four fields
    reach every place a figure from this brief can end up. Returns "" for an
    empty registry so a caller can append it unconditionally.
    """
    if not entries:
        return ""

    lines = ["%s:" % heading] if heading else []
    for entry in entries:
        lines.append("%s — %s" % (entry["section"], format_provenance_line(entry)))
    return "\n".join(lines)
